/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package org.uv.programaclase07cc;

import java.time.Instant;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.uv.programaclase07cc.percistence.DAOVenta;
import org.uv.programaclase07cc.percistence.DetalleVenta;
import org.uv.programaclase07cc.percistence.Venta;

/**
 *
 * @author fermin
 */
public class ProductoGUI extends javax.swing.JInternalFrame {
    DefaultTableModel dtm= new DefaultTableModel();
    List<DetalleVenta> productos=new ArrayList<>();
    DAOVenta dao=new DAOVenta();
    /**
     * Creates new form ProductoGUI
     */
    DAOVenta venta;
    public ProductoGUI() {
        initComponents();
        String [] titulo= new String[]{"ID","Cantidad","Descripcion","Precio","subtotal","IdVenta"};
        dtm.setColumnIdentifiers(titulo);
        tblProductos.setModel(dtm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        btnAgrProd = new javax.swing.JButton();
        txtIdVenta = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnEdtProd = new javax.swing.JButton();
        btnBrVenta = new javax.swing.JButton();
        btnAgrVenta = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Catalogo de Productos");

        jLabel1.setText("Descripcion: ");

        jLabel2.setText("Cantidad: ");

        jLabel3.setText("Precio: ");

        btnAgrProd.setText("Agregar Producto");
        btnAgrProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgrProdActionPerformed(evt);
            }
        });

        jLabel5.setText("Id Venta: ");

        btnEdtProd.setText("Editar Productos");
        btnEdtProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEdtProdActionPerformed(evt);
            }
        });

        btnBrVenta.setText("Borrar Venta");
        btnBrVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrVentaActionPerformed(evt);
            }
        });

        btnAgrVenta.setText("Agregar Venta");
        btnAgrVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgrVentaActionPerformed(evt);
            }
        });

        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblProductos.setEnabled(false);
        jScrollPane1.setViewportView(tblProductos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtIdVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtPrecio)
                        .addComponent(txtCantidad)
                        .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAgrProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEdtProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBrVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAgrVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgrProd)
                    .addComponent(txtIdVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEdtProd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBrVenta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgrVenta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgrProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgrProdActionPerformed
        if(txtCantidad.getText().isEmpty()||txtDescripcion.getText().isEmpty()||txtPrecio.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Algun campo esta vacio!!!");
        }
        else{
            double cant=Double.parseDouble(txtCantidad.getText());
            double prec= Double.parseDouble(txtPrecio.getText());
            double subtotal=cant*prec;
            DetalleVenta det= new DetalleVenta();
            det.setCantidad(cant);
            det.setDescripcion(txtDescripcion.getText());
            det.setPrecio(prec);
            det.setSubtotal(subtotal);  
            dtm.addRow(new Object[]{"",txtCantidad.getText(),txtDescripcion.getText(),txtPrecio.getText(),String.valueOf(subtotal),""});
            productos.add(det);
            this.txtCantidad.setText("");
            this.txtDescripcion.setText("");
            this.txtPrecio.setText("");
        }
        
    }//GEN-LAST:event_btnAgrProdActionPerformed

    private void btnEdtProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEdtProdActionPerformed
        Venta vent;
        Date fecha= Date.from(Instant.now());
        
        if(txtIdVenta.getText().isEmpty()||productos.isEmpty()){
            JOptionPane.showMessageDialog(null, "Campos Vacios!!");
        }
        else{
            int id = Integer.parseInt(txtIdVenta.getText());
            vent = new Venta();
            vent.setFecha(new java.sql.Date(fecha.getTime()));
            double monto = 0;
            for (DetalleVenta producto : productos) {
                producto.setVenta(vent);
                monto = monto + producto.getSubtotal();
                vent.getDetalle().add(producto);
            }
            vent.setMonto(monto);
            if (dao.update(id, vent) != null) {
                for (int i = dtm.getRowCount() - 1; i > -1; i--) {
                    dtm.removeRow(i);
                }
                JOptionPane.showMessageDialog(null, "Se agrego correctamente");
                this.txtCantidad.setText("");
                this.txtDescripcion.setText("");
                this.txtPrecio.setText("");
                for (DetalleVenta p : vent.getDetalle()) {
                    dtm.addRow(new Object[]{
                        String.valueOf(p.getIdProducto()), String.valueOf(p.getCantidad()), String.valueOf(p.getDescripcion()), String.valueOf(p.getPrecio()), String.valueOf(p.getSubtotal()), txtIdVenta
                    });
                }
                productos = null;
            } else {
                JOptionPane.showMessageDialog(null, "Error al agregar");
            }
        }
    }//GEN-LAST:event_btnEdtProdActionPerformed

    private void btnBrVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrVentaActionPerformed
        if(txtIdVenta.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Escribar el id de la venta!!");
        }
        else{
            int id= Integer.parseInt(txtIdVenta.getText());
            boolean res=dao.delete(id);
            if(res){
                JOptionPane.showMessageDialog(null, "Se ha borrado la venta");
                this.txtIdVenta.setText("");
                this.txtCantidad.setText("");
                this.txtDescripcion.setText("");
                this.txtPrecio.setText("");
            }
            else{
                JOptionPane.showMessageDialog(null, "No existe la venta");
            }
        }
    }//GEN-LAST:event_btnBrVentaActionPerformed

    private void btnAgrVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgrVentaActionPerformed
        Venta vent;
        Date fecha= Date.from(Instant.now());
        if(productos.isEmpty()){
            JOptionPane.showMessageDialog(null, "No existen productos para la venta!!");
        }
        else{
            vent = new Venta();
            vent.setFecha(new java.sql.Date(fecha.getTime()));
            double monto = 0;
            for (DetalleVenta producto : productos) {
                producto.setVenta(vent);
                monto = monto + producto.getSubtotal();
                vent.getDetalle().add(producto);
            }
            vent.setMonto(monto);
            if (dao.create(vent) != null) {
                if (dtm.getRowCount() > 0) {
                    for (int i = dtm.getRowCount() - 1; i > -1; i--) {
                        dtm.removeRow(i);
                    }
                }
                JOptionPane.showMessageDialog(null, "Se agrego correctamente");
                this.txtCantidad.setText("");
                this.txtDescripcion.setText("");
                this.txtPrecio.setText("");
                for (DetalleVenta p : vent.getDetalle()) {
                    dtm.addRow(new Object[]{
                        String.valueOf(p.getIdProducto()), String.valueOf(p.getCantidad()), String.valueOf(p.getDescripcion()), String.valueOf(p.getPrecio()), String.valueOf(p.getSubtotal()), String.valueOf(vent.getIdVenta())
                    });
                }
                productos=null;
            } else {
                JOptionPane.showMessageDialog(null, "Error al agregar");
            }   
        }
    }//GEN-LAST:event_btnAgrVentaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgrProd;
    private javax.swing.JButton btnAgrVenta;
    private javax.swing.JButton btnBrVenta;
    private javax.swing.JButton btnEdtProd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProductos;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtIdVenta;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
