/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package org.uv.programaclase07cc;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import org.uv.programaclase07cc.percistence.DAOVenta;
import org.uv.programaclase07cc.percistence.DetalleVenta;
import org.uv.programaclase07cc.percistence.Venta;

/**
 *
 * @author fermin
 */
public class VentaProductoGUI extends javax.swing.JInternalFrame {
    DefaultTableModel dtm;
    DAOVenta dao=new DAOVenta();
    /**
     * Creates new form VentaProducto
     */
    public VentaProductoGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        btnBusVent = new javax.swing.JButton();
        btnBusProdsByV = new javax.swing.JButton();
        btnListVent = new javax.swing.JButton();
        btnListProds = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGnl = new javax.swing.JTable();

        setClosable(true);
        setTitle("Ventas - Productos");

        jLabel1.setText("ID: ");

        btnBusVent.setText("Buscar Venta");
        btnBusVent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBusVentActionPerformed(evt);
            }
        });

        btnBusProdsByV.setText("Buscar Productos por Venta");
        btnBusProdsByV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBusProdsByVActionPerformed(evt);
            }
        });

        btnListVent.setText("Lista Ventas");
        btnListVent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListVentActionPerformed(evt);
            }
        });

        btnListProds.setText("Lista Productos");
        btnListProds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListProdsActionPerformed(evt);
            }
        });

        tblGnl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblGnl.setEnabled(false);
        jScrollPane1.setViewportView(tblGnl);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnListVent))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBusVent, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBusProdsByV)
                            .addComponent(btnListProds, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(7, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBusProdsByV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBusVent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnListVent)
                    .addComponent(btnListProds))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBusVentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusVentActionPerformed
        dtm= new DefaultTableModel();
        String [] titulo= new String[]{"Id Venta","Fecha","Monto"};
        dtm.setColumnIdentifiers(titulo);
        tblGnl.setModel(dtm);
        int id= Integer.parseInt(txtId.getText());
        Venta venta=dao.findById(id);
        dtm.addRow(new Object[]{
            String.valueOf(venta.getIdVenta()), String.valueOf(venta.getFecha()), String.valueOf(venta.getMonto())
        });
    }//GEN-LAST:event_btnBusVentActionPerformed

    private void btnBusProdsByVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusProdsByVActionPerformed
        dtm= new DefaultTableModel();
        String [] titulo= new String[]{"ID","Cantidad","Descripcion","Precio","subtotal","IdVenta"};
        dtm.setColumnIdentifiers(titulo);
        tblGnl.setModel(dtm);
        int id= Integer.parseInt(txtId.getText());
        Venta venta=dao.findById(id);
        for (DetalleVenta p : venta.getDetalle()) {
            dtm.addRow(new Object[]{
                String.valueOf(p.getIdProducto()), String.valueOf(p.getCantidad()), String.valueOf(p.getDescripcion()), String.valueOf(p.getPrecio()), String.valueOf(p.getSubtotal()), String.valueOf(venta.getIdVenta())
            });
        }
    }//GEN-LAST:event_btnBusProdsByVActionPerformed

    private void btnListVentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListVentActionPerformed
        dtm= new DefaultTableModel();
        String [] titulo= new String[]{"Id Venta","Fecha","Monto"};
        dtm.setColumnIdentifiers(titulo);
        tblGnl.setModel(dtm);
        List<Venta> ventas=dao.findAll();
        for (Venta venta : ventas) {
            dtm.addRow(new Object[]{
                String.valueOf(venta.getIdVenta()),String.valueOf(venta.getFecha()),String.valueOf(venta.getMonto())
            });
        }
    }//GEN-LAST:event_btnListVentActionPerformed

    private void btnListProdsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListProdsActionPerformed
        // TODO add your handling code here:
        dtm= new DefaultTableModel();
        String [] titulo= new String[]{"ID","Cantidad","Descripcion","Precio","subtotal","IdVenta"};
        dtm.setColumnIdentifiers(titulo);
        tblGnl.setModel(dtm);
        List<Venta> ventas=dao.findAll();
        for (Venta venta : ventas) {
            for (DetalleVenta p : venta.getDetalle()) {
                dtm.addRow(new Object[]{
                    String.valueOf(p.getIdProducto()),String.valueOf(p.getCantidad()),String.valueOf(p.getDescripcion()),String.valueOf(p.getPrecio()),String.valueOf(p.getSubtotal()),String.valueOf(venta.getIdVenta())
                });
            }
        }
    }//GEN-LAST:event_btnListProdsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBusProdsByV;
    private javax.swing.JButton btnBusVent;
    private javax.swing.JButton btnListProds;
    private javax.swing.JButton btnListVent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblGnl;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables
}
